name: Check version and publish package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish package
	      run: |
      		npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
      		npm config set @soph2k:registry=https://npm.pkg.github.com/ 
      		npm publish

	  
