name: Check version and publish package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compare_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish package
        run: npm publish
